### ISSUE TITLE
OAuth error

### ISSUE THREAD

**Issue by Gonzih** [owainlewis/hipchat#5]
Hi, I was playing with your library and was unable to reproduce examples from readme.
Looks like readme is outdated (with-token accepts not a string but something that can be derefed).
Also some examples in readme contain trailing parenthesis.

But when I'm trying to do calls to api with global token configured I'm getting following error:

```clojure
{:status 401, :body {:error {:code 401, :message "Invalid OAuth session", :type "Unauthorized"}}}
``` 

Am I doing something wrong? Thank you.

**Comment by VFe** [comment]
Same, doesn't work in either fashion.

**Comment by owainlewis** [comment]
Hi. Thanks for pointing this out. I'll take a look tomorrow. Sorry about this.

**Comment by VFe** [comment]
Appreciate it, thanks!

**Comment by BinarySplit** [comment]
I was having similar issues. It turns out I was using the wrong type of token. HipChat has 2 types of API tokens: 

* organisation-level tokens for the v1 API that are ~30 lower-case hexadecimal characters. They can be created here: https://www.hipchat.com/admin/api (needs org-level admin access)
* user-level tokens for the v2 API that are ~40 mixed-case alphanumeric characters. They can be created here: https://www.hipchat.com/account/api

Try again with a user-level token. You should only get 401s if your token is invalid - otherwise you'll get 403s if you've got the wrong permissions.

**Comment by Gonzih** [comment]
@BinarySplit yeah, you are right. User level tokens work fine. Shall this be closed then?

**Comment by owainlewis** [comment]
Yeah happy to close. Thanks :+1:
